### ISSUE TITLE
Ubuntu 14.04 quick-start failure

### ISSUE THREAD

**Issue by tbird20d** [electron/electron-quick-start#82] opened 2016-09-07 23:07 UTC
On Ubuntu 14.04, I did:

$ sudo apt-get install npm
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
$ npm install && npm start

And eventually got:

...
npm http GET https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz

> electron@1.3.5 postinstall /home/1000072457/work/electron/electron-quick-start/node_modules/electron
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
$

I don't know if this is from something I preinstalled or not.  I tried 'sudo apt-get install node', but got the same error.

**Comment by jlord** [comment] 2016-09-07 23:21
It doesn't look like you have Node properly installed. The `apt-get` package you actually want is called `nodejs` and not `node`.

```
sudo apt-get install nodes
```

I've used these distributions myself: https://github.com/nodesource/distributions.

**Comment by tbird20d** [comment] 2016-09-07 23:55
Wow - Thanks for the quick response.

Hmmm.  I have nodejs installed.

$ dpkg -l | grep nodejs
ii  nodejs                                                0.10.25~dfsg2-2ubuntu1                              amd64        evented I/O for V8 javascript
ii  nodejs-dev                                            0.10.25~dfsg2-2ubuntu1                              amd64        evented I/O for V8 javascript (development files)

I looked back and saw these warnings running npm:
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})

Would this explain the error (nodejs too old)?

Are you saying I should replace the default ubuntu nodejs with one from nodesource?

**Comment by jlord** [comment] 2016-09-08 00:39
Oh, yeah, you should upgrade that version of Node. The LTS at 4.5.0 is a good one to get on 👍 

It's up to you which route you go for upgrading, I saw that `sudo apt-get install nodejs` exists and wanted to highlight that since it was most similar to what you were already doing but from personal experience I can only speak to using the NodeSource distributions.

**Comment by Haacked** [comment] 2016-09-23 20:55
@tbird20d did @jlord's suggestion work for you?

**Comment by tbird20d** [comment] 2016-09-25 02:02
>________________________________
> From: Phil Haack <notifications@github.com>
>To: electron/electron-quick-start <electron-quick-start@noreply.github.com> 
>Cc: Tim Bird <tbird20d@yahoo.com>; Mention <mention@noreply.github.com>
>Sent: Friday, September 23, 2016 1:55 PM
>Subject: Re: [electron/electron-quick-start] Ubuntu 14.04 quick-start failure (#82)
> 
>
>
>@tbird20d did @jlord's suggestion work for you?
>


No.  I fiddled with it a bit more, but couldn't figure out how to replace
the nodejs that Ubuntu was providing with the one from the web site.  To be
fair, I didn't really investigate it much more.
 -- Tim

**Comment by Haacked** [comment] 2016-09-26 16:51
> To be fair, I didn't really investigate it much more.

Ok, I'll close the issue then. If you want to investigate more, we'd be happy to help. Just comment again and we can re-open it.

You might experiment with the NVM approach mentioned in this blog post: https://davidwalsh.name/nvm

**Closed by Haacked** 2016-09-26 16:51 UTC

**Comment by tbird20d** [comment] 2016-09-27 22:08
>________________________________
> From: Phil Haack <notifications@github.com>
>To: electron/electron-quick-start <electron-quick-start@noreply.github.com> 
>Cc: Tim Bird <tbird20d@yahoo.com>; Mention <mention@noreply.github.com>
>Sent: Monday, September 26, 2016 9:51 AM
>Subject: Re: [electron/electron-quick-start] Ubuntu 14.04 quick-start failure (#82)
> 
>
>
>To be fair, I didn't really investigate it much more.
>Ok, I'll close the issue then. If you want to investigate more, we'd be happy to help. Just comment again and we can re-open it.
>You might experiment with the NVM approach mentioned in this blog post: https://davidwalsh.name/nvm


I don't care if it works or not.  I was just reporting that your quick start guide is wrong.
Did anyone change anything in the quickstart guide?
 -- Tim

**Comment by Haacked** [comment] 2016-09-27 22:40
> Did anyone change anything in the quickstart guide?

Not that I know of. We've been unable to reproduce your results following the same steps.
