### ISSUE TITLE
npm start does not work | electron command displays nothing | Exit status 3221225781 => (Solution)

### ISSUE THREAD

**Issue by rodryquintero** [electron/electron-quick-start#55] opened 2016-05-17 18:49 UTC
Just in case this helps anyone. Make sure you have the Visual [C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) for your specific platform. If you don't you may get this errors in the `npm-debug.log` file when trying to run `npm start`.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Propietario-1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.9.0
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: C:\Users\Propietario-1\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Propietario-1\Documents\GitHub\electron-quick-start-master\node_modules\.bin;C:\Program Files\nodejs;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\wamp\bin\php\php5.3.13;C:\wamp\www\phalcon-devtools-master;C:\Python27;C:\Python27\Scripts;C:\OpenSSL-Win32\bin;C:\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\JSONBuddy;C:\Users\Propietario-1\AppData\Local\atom\bin;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Propietario-1\AppData\Roaming\npm;C:\Program Files\nodejs\node
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: C:\Users\Propietario-1\Documents\GitHub\electron-quick-start-master
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '/d /s /c', 'electron main.js' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 3221225781  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
14 verbose stack Exit status 3221225781
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Propietario-1\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Propietario-1\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd C:\Users\Propietario-1\Documents\GitHub\electron-quick-start-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Propietario-1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.1.0
20 error npm  v3.9.0
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 start: `electron main.js`
22 error Exit status 3221225781
23 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
After installing the problem was solved. I found the solution in this [link](https://discuss.atom.io/t/electron-error-when-running-app-and-blank-output-from-electron-in-command-line/28976/3).

**Comment by jlord** [comment] 2016-05-20 18:30
Thanks for the tip! Closing as dupe of #54.

**Closed by jlord** 2016-05-20 18:30 UTC
