### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by IceWee** [electron/electron-quick-start#108] opened 2016-11-21 07:00 UTC
HI, i try run "npm start", but failed, that's err info below, help me,please, thks!

[root@bing electron-quick-start]# node -v
v6.0.0
[root@bing electron-quick-start]# npm -v
3.8.6
[root@bing electron-quick-start]# npm start

> electron-quick-start@1.0.0 start /root/git/electron-quick-start
> electron .

**> /root/git/electron-quick-start/node_modules/electron/dist/electron: symbol lookup error: /root/git/electron-quick-start/node_modules/electron/dist/electron: undefined symbol: g_bytes_unref**

npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/git/electron-quick-start/npm-debug.log

**Comment by IceWee** [comment] 2016-11-21 07:01
there's no '/root/git/electron-quick-start/node_modules/electron/path.txt' file, likely a windows file, why open it?

**Comment by MarshallOfSound** [comment] 2016-11-21 07:08
> likely a windows file, why open it?

It is not a windows specific file, that file should be there for all OS's

If that file is missing your node_modules install probably glitched out, it happens sometimes.  Just delete your node_modules folder and re run `npm install`

**Comment by IceWee** [comment] 2016-11-21 10:19
problems updated...

**Comment by zeke** [comment] 2016-11-21 23:49
@IceWee please try this and let us know what you see:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

**Comment by cassidoo** [comment] 2016-11-22 00:45
I get the same error.  Did these steps:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

And then I tried `npm install -g electron` to see if that fixed it (it didn't):

```
.../electron-quick-start$ npm start

> electron-quick-start@1.0.0 start .../electron-quick-start
> electron .

.../electron-quick-start/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     .../electron-quick-start/npm-debug.log
```

I'm running this on bash on Windows.

**Comment by IceWee** [comment] 2016-11-22 01:16
Thanks, everyone, I have upgraded to CentOS 7, now it's OK.

**Comment by zeke** [comment] 2016-11-22 01:31
@IceWee glad you worked it out!

@cassidoo it looks like this line is the culprit:

> error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Try this:

```
apt-get install libgtk2.0-0 
```

via http://stackoverflow.com/questions/38935024/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0

**Comment by IceWee** [comment] 2016-11-22 01:51
@zeke Thks!!

**Comment by drfischer** [comment] 2016-12-14 05:15
I have a similar problem on Windows. I installed as described above:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

and got 

```
> electron-quick-start@1.0.0 start H:\Code\electron\electron-quick-start
> electron .

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (H:\Code\electron\electron-quick-start\node_modules\electron\cli.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\Code\electron\electron-quick-start\npm-debug.log
```

I have, however, also a global installation of electron, so I could run the code using

```
electron .
```

After removing (or renaming) `node_modules` from `electron-quick-start`, I could also launch it using:

```
npm start
```

My first thought was that the local `dist/electron.exe` is not being found for whatever reasons. This is, however, not the case. If I use the local electron installation and just rename the .exe, I get a different error:

```
> electron-quick-start@1.0.0 start H:\Code\electron\electron-quick-start
> electron .

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn H:\Code\electron\electron-quick-start\node_modules\electron\dist\electron.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Any suggestions?

**Comment by bratsos** [comment] 2017-02-12 23:06
I'm also facing the same issue. I tried everything on the internet to solve this like: install all missing dependancies (libgtk, libtstxso etc), install Visual C++ Redistributable for Visual Studio 2015 for both x64/x86 (already installed), rm -rf node_modules and install it again (with --verbose too). Nothing seems to work. npm start gives the dreadful ELIFECYLCE error exit status 1.

I also noticed that even though there's an error, if I start the task manager, there's an "Electron" process sitting there peacefully. Same happened by running "electron . " on command line - no output, but there's a process on task manager. 

OS is win10 with base, node v4.2.6 npm 4.2.0

**Comment by zeke** [comment] 2017-02-15 19:35
@bratsos are you still having trouble?

**Comment by bratsos** [comment] 2017-02-15 20:01
@zeke According to [this answer](https://github.com/electron/electron-quick-start/issues/129#issuecomment-279701745) the problem is caused by windows's bash implementation. I installed NodeJS for windows and Git for windows to get around that - it's ugly but it works.

I think there should be a warning on the readme about windows bash and electron, since 9/10 issues with the keywords "Windows" and "npm start" are caused by this.

**Comment by zeke** [comment] 2017-02-15 21:41
> I think there should be a warning on the readme about windows bash and electron

💡 Good idea. Want to take a crack at pull request adding this info?

Looks like all the various problems reported here have been sorted, so I'm closing this out.

**Closed by zeke** 2017-02-15 21:41 UTC

**Comment by atlabiz** [comment] 2017-06-09 09:55
OMG i have this error when i run npm start 

```node
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Developer\Documents\GitHub\George35mk projects\electron-quick-start\node_modules\electron\dist\electron.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Developer\AppData\Roaming\npm-cache\_logs\2017-06-09T09_54_46_958Z-debug.log

C:\Users\Developer\Documents\GitHub\George35mk projects\electron-quick-start>



```

**Comment by arjunkesava** [comment] 2017-06-19 17:44
Even I have the same issue as mentioned above, How to resolve it

**Comment by JoshBezs** [comment] 2017-10-13 08:36
@MarshallOfSound Thanks, the solution with deleting node_module works for me.

**Comment by orangelin** [comment] 2017-11-02 08:50
`
[root@sir electron-quick-start]# npm start

> electron-quick-start@1.0.0 start /home/sulinorange/electron-quick-start
> electron .


npm ERR! Linux 3.10.0-693.5.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sulinorange/electron-quick-start/npm-debug.log
`
so why?

**Comment by JoshBezs** [comment] 2017-11-02 15:35
@orangelin Please provide the whole project structure.
Example: 
Project name:
--main.js
--node_modules/
--package.json
Also can you please show us the log:
/home/sulinorange/electron-quick-start/npm-debug.log

**Comment by nur-kholis** [comment] 2017-12-03 03:18
i am having the same problem. it happens because npm has not completed its task. I deleted the node_module folder and ran the npm install again. and now works well

**Comment by Castor243** [comment] 2018-04-16 13:13
hi! i have the same problem. my log here. thanks
[2018-04-16T13_56_59_728Z-debug.log](https://github.com/electron/electron-quick-start/files/1915375/2018-04-16T13_56_59_728Z-debug.log)

**Comment by Jagat-sdrc** [comment] 2018-05-05 07:42
Error: Generated checksum for "electron-v1.8.4-win32-x64.zip" did not match expected checksum.
    at Hash.hasher.on (E:\Jagat\Electron\electrom_demo\node_modules\sumchecker\index.js:151:20)
    at emitNone (events.js:106:13)
    at Hash.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Hash.Readable.push (_stream_readable.js:208:10)
    at Hash.Transform.push (_stream_transform.js:147:32)
    at Hash._flush (crypto.js:93:8)
    at Hash.prefinish (_stream_transform.js:137:10)
    at emitNone (events.js:106:13)
    at Hash.emit (events.js:208:7)
    at prefinish (_stream_writable.js:593:14)
    at finishMaybe (_stream_writable.js:601:5)
    at endWritable (_stream_writable.js:612:3)
From previous event:
    at Packager.packager.electronDownloader.options [as electronDownloader] (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder\src\builder.ts:227:12)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\electron\ElectronFramework.ts:148:21
    at Generator.next (<anonymous>)
From previous event:
    at unpack (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\electron\ElectronFramework.js:221:18)
    at Object.prepareApplicationStageDirectory (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\electron\ElectronFramework.ts:125:50)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\platformPackager.ts:177:21
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doPack (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\platformPackager.js:410:7)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\platformPackager.js:275:7)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (E:\Jagat\Electron\electrom_demo\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at E:\Jagat\Electron\electrom_demo\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\packager.js:615:7)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\packager.ts:317:52
    at Generator.next (<anonymous>)
    at E:\Jagat\Electron\electrom_demo\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\Jagat\Electron\electrom_demo\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\packager.js:542:7)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\packager.js:501:7)
    at E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder\src\builder.ts:229:10)
    at then (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder\src\cli\cli.ts:43:10)
    at Object.runCommand (E:\Jagat\Electron\electrom_demo\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\Jagat\Electron\electrom_demo\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (E:\Jagat\Electron\electrom_demo\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (E:\Jagat\Electron\electrom_demo\node_modules\electron-builder\src\cli\cli.ts:28:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 dist: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SDRC_PC_08\AppData\Roaming\npm-cache\_logs\2018-05-05T07_38_49_567Z-debug.log

**Comment by sayantanHack** [comment] 2019-04-05 18:39
same issue happening in windows.This is showing bellow
error code ELIFECYCLE
error errno 1
error electron-quick-start@1.0.0 start: electron .
error Exit status 1
error Failed at the electron-quick-start@1.0.0 start script.
error This is probably not a problem with npm. There is likely additional logging output above.
verbose exit [ 1, true ]

**Comment by alexruma** [comment] 2019-04-20 22:06
@sayantanHack  did you solve this? I'm getting to exact same error message.

**Comment by Neguhs** [comment] 2019-04-23 14:55
Currently experiencing similar issue when using npm start 
 npm ERR! code ELIFECYCLE
npm ERR! errno 77
npm ERR! test@1.0.0 start: `electron .`
npm ERR! Exit status 77
npm ERR!
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov

**Comment by shadywattay** [comment] 2019-04-27 09:11
I'm having the same problem. anyone with help out there...

```
# npm start

> your-app@0.1.0 start /var/www/html/electron
> electron .

sh: 1: electron: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! your-app@0.1.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the your-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-27T09_08_40_161Z-debug.log
```

**Comment by Neguhs** [comment] 2019-04-28 00:20
Is electron installed/ are you requiring on the correct files ? Or can you post the full complete log

**Comment by alexruma** [comment] 2019-04-29 00:23
I was able to get around this by running $ ./node_modules/.bin/electron .

**Comment by Burstality** [comment] 2019-07-07 07:44
did you solve the issue @Neguhs, having the same exact error message.

**Comment by thomashare** [comment] 2019-10-04 19:23
running 'npm rebuild' helped resolve the issue for me.

**Comment by sayantanHack** [comment] 2019-10-04 19:43
You can also run npm audit  and npm audit fix . This can work for this.

**Comment by CarlosTingu** [comment] 2019-10-08 18:08
You have to give all permissions, in case linux is just a chmod 777 -R Here is the directory /

**Comment by midhunomk** [comment] 2020-04-18 08:21
> electron-quick-start@1.0.0 start /home/smecmidhun/electron-quick-start
> electron .


(electron:29973): Gtk-WARNING **: 08:20:31.401: cannot open display: :0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by amin-hub-programer** [comment] 2020-08-27 05:56
**$ npm start**

> electron-quick-start@1.0.0 start /home/charon/electron-quick-start
> electron .

[6138:0827/102451.435886:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/charon/electron-quick-start/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/home/charon/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/charon/.npm/_logs/2020-08-27T05_54_51_467Z-debug.log

**Comment by Marcosul** [comment] 2020-10-17 13:40
Any help, please?
I'm having the same problem. anyone with help out there...
OS: Ubuntu

$ npm start

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marco/.npm/_logs/2020-10-17T13_38_37_519Z-debug.log

**Comment by amin-hub-programer** [comment] 2020-10-17 15:35
I no longer work with Linux . sorry

‫‪Marco Aurélio Sulzbacher‬‏ <‪notifications@github.com‬‏> در تاریخ شنبه ۱۷
اکتبر ۲۰۲۰ ساعت ۱۷:۱۱ نوشت:‬

**Comment by amin-hub-programer** [comment] 2020-10-17 15:52
What development are you using?kali or ubuntu or ....

‫‪Marco Aurélio Sulzbacher‬‏ <‪notifications@github.com‬‏> در تاریخ شنبه ۱۷
اکتبر ۲۰۲۰ ساعت ۱۷:۱۱ نوشت:‬

**Comment by Eliosth** [comment] 2020-11-29 07:43
> 
> 
> You can also run npm audit and npm audit fix . This can work for this.

this works for me , thank you so much

**Comment by benlesh** [comment] 2021-11-24 23:51
I'm having this issue. Following the [steps outlined in the comment above](https://github.com/electron/electron-quick-start/issues/108#issuecomment-262104601) by @zeke

The ONLY thing I see though is just:

```
npm start

> electron-quick-start@1.0.0 start
> electron .

/home/benlesh/GitHub/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGTRAP
```

Nothing actionable or helpful at all.

**Comment by erickzhao** [comment] 2021-11-25 00:46
@benlesh The SIGTRAP might be the following issue: https://github.com/electron/electron/issues/31885

What happens if you downgrade Electron to 15.3.0?

**Comment by NOPR9D** [comment] 2021-12-09 20:33
Same issue...

Error :
![image](https://user-images.githubusercontent.com/75882457/145471336-9223beca-ddf7-4aa7-a2fd-a4141dbc7bed.png)

My package.json :
![image](https://user-images.githubusercontent.com/75882457/145471270-4ebfe852-c617-49f0-8ea2-1df0597c0fb4.png)

My config (and npm 8.1 with windows 10 wsl) :
![image](https://user-images.githubusercontent.com/75882457/145471391-c903df30-deb7-4807-aba9-c5f3742b9568.png)

**Comment by gerardparareda** [comment] 2022-03-13 23:58
Why has this been closed? I'm running the WSL and I too keep getting:

`my-electron-app/node_modules/electron/dist/electron exited with signal SIGTRAP`

I tried every possible solution on here (`npm audit`, deleting `node_modules` and reinstalling, giving permissions, etc.). Can someone even point a possible point of failure?
