### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by IsaacHome** [electron/electron-quick-start#186] opened 2018-02-12 15:25 UTC
Hi there, i am new to electron and testing Ubuntu 17.10 and when i run and i got the following error.

isaachome@dell:~/Desktop/Electron/shoppinglist$ npm start

> shoppinglist@1.0.0 start /home/isaachome/Desktop/Electron/shoppinglist
> electron .

/home/isaachome/Desktop/Electron/shoppinglist/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

npm ERR! Linux 4.13.0-21-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! shoppinglist@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the shoppinglist@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shoppinglist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shoppinglist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shoppinglist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/isaachome/Desktop/Electron/shoppinglist/npm-debug.log

**Comment by ckerr** [comment] 2018-03-12 13:10
This appears to be a duplicate of https://github.com/electron/electron/issues/1518

**Closed by ckerr** 2018-03-12 13:10 UTC
