### ISSUE TITLE
npm start: code ELIFECYCLE; errorno 1

### ISSUE THREAD

**Issue by albertStaalburger** [electron/electron-quick-start#189] opened 2018-02-19 21:30 UTC
I am trying to get `quick-start` up and running in a vagrant box.
I followed this post: [https://flatmap.it/2016/10/25/vagrant-electron/](url) to get the box set-up.
System info:
Box: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-141-generic x86_64)
Node: v8.2.1
Npm: v5.3.0

I have read through the other similar errors and searched the web for quite a few hours.
I know it is not my `Node` version that is the issue as in most other cases.

When running `npm start` I get the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-02-19T21_08_55_663Z-debug.log
```
Opening the log file gives me:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v8.2.1/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v8.2.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/Code/electron-quick-start/node_modules/.bin:/home/vagrant/.nvm/versions/node/v8.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/vagrant/Code/electron-quick-start
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/vagrant/Code/electron-quick-start
16 verbose Linux 3.13.0-141-generic
17 verbose argv "/home/vagrant/.nvm/versions/node/v8.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v8.2.1/bin/npm" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I am at a loss as to what is causing this error.
Any guidance or pointers would be appreciated...

**Comment by Baonui9999** [comment] 2018-02-28 11:11
Dee jai https://m.xhamster.commake

**Comment by ckerr** [comment] 2018-03-12 13:50
Closing this as a duplicate of #155

**Closed by ckerr** 2018-03-12 13:50 UTC

**Comment by xavierluz** [comment] 2019-05-01 22:59
I reinstalled the webpack and it worked

>   "npm i --save-dev webpack@1.14.0"
