### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by gilbitron** [electron/electron-quick-start#113] opened 2016-11-28 14:56 UTC
Following the "Quick Start" on the Electron homepage I get the following error. I did have electron installed globally but has since been removed. Does anyone have any ideas?

* macOS 10.12.1
* Node 7.2.0
* Npm 3.10.9

Note I've removed the path to my project in the log below:

```
> electron-quick-start@1.0.0 start /...
> electron .

/.../main.js:40
app.on('ready', createWindow)
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/.../main.js:40:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
```

**Comment by gilbitron** [comment] 2016-11-28 15:20
Looks like I'm not the only one having this problem https://github.com/electron/electron/issues/4017

**Comment by TacoCoder** [comment] 2016-11-29 03:24
Having this issue as well.

Here is what I've done:
* Updating node/npm
* Using `electron-prebuilt` instead of electron
* Made sure electron was not installed globally
* Deleted `node_modules` and re-ran `npm install`

Here is the error message:
```
app.on('ready', createWindow());
   ^


TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/home/harry/web/webcalc/app.js:17:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
```

Node version: `v7.2.0`
NPM version: `4.0.2`
Electron version: `1.4.10`

System is GNU/Linux running Linux Mint 18 Cinnamon 64 Bit

**Comment by MarshallOfSound** [comment] 2016-11-29 03:51
@TacoCoder Are you using tmux?

**Comment by TacoCoder** [comment] 2016-11-29 03:52
@MarshallOfSound No sir

**Comment by TacoCoder** [comment] 2016-11-29 03:54
Got it working :D I don't exactly know why but electron didn't like being run from Atom's `terminal plus` plugin. Went and ran it in an actual terminal and it worked fine.. I'll look into why this is.

**Comment by gilbitron** [comment] 2016-11-29 09:31
> electron didn't like being run from Atom's terminal plus plugin. Went and ran it in an actual terminal and it worked fine.

@TacoCoder Yep that's the one. Just confirmed that it runs fine for me if I use another terminal.

**Comment by 3rd-Eden** [comment] 2016-11-30 08:47
Having the same issues. 

- I tried running `terminal` instead of `iTerm`, same problem. 
- Open fresh terminal, run `bash` so i'm no longer in `zsh` run the app, same problem.

**Comment by stoffeastrom** [comment] 2016-12-05 13:56
I have the same error message and it doesn't matter which terminal I try :/

**Comment by cnwalker** [comment] 2017-01-03 19:42
@TacoCoder also had the same issue and it was fixed by using the regular terminal. Thanks!

**Comment by JustinBeckwith** [comment] 2017-01-07 02:47
Same for me.  I randomly started getting this error.  I've tried:
- `npm uninstall -g electron`
- Checking my nvm global npm cache
- Making sure electron was installed in my project as a dev dependency only

Still, app is coming back as undefined - even though the window launches.

**Comment by zeke** [comment] 2017-01-11 23:05
@JustinBeckwith if you're still having issues, try this:

```
git clone https://github.com/electron/electron-quick-start quickie
cd quickie
npm install
npm start
```

...then let us know what you see.

Also, as others above have noted, running the app from within tmux or from an Atom plugin can cause issues.

**Comment by JustinBeckwith** [comment] 2017-01-13 08:16
In case this helps anyone else - I figured out what was causing my issues.  It was user error with webpack *hangs head*.  I was accidentally bundling my main process script in with my renderer scripts, and it was trying to run main in the browser.  I was running `webpack .` instead of `webpack`, which meant it was ignoring my `webpack.config.js`.  It defaulted to choosing main.js as my entrypoint, and well...  yeah.  It explains why everything was actually working, despite the errors in the console. 

Thanks!

**Comment by zeke** [comment] 2017-01-13 18:42
Closing this out, as everyone seems to determined that the problem is caused by tmux and/or an atom plugin.

**Closed by zeke** 2017-01-13 18:42 UTC

**Comment by sarahmonks** [comment] 2017-05-29 13:16
I had the same error. But it works after i did the following:

1. I deleted the node_modules folder in my project
2. I ran npm install again in my project folder

hope that helps

**Comment by soware** [comment] 2018-03-08 21:22
I solve in my case changing the package.json
was:

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },

and I changed to:

"scripts": {
    "start": "electron ."
  },

**Comment by odio4u** [comment] 2019-03-09 21:06
try to run this from command window it has been worked for me.
