### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by liyuanqiu** [electron/electron-quick-start#179] opened 2017-12-22 08:20 UTC
I install electron-quick-start in a brand new, clean, pure debian 9.2 environment.

My steps:
1. Create a cloud server with debian 9.2 as its OS in the cloud provider(Aliyun)
2. Install NodeJS 8 as the offical instruction:
```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
3. Install and run electron as your instruction:
```bash
# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start
```

Then I got the error output:
```
> electron@1.7.10 postinstall /root/electron-quick-start/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 152 packages in 32.555s

> electron-quick-start@1.0.0 start /root/electron-quick-start
> electron .

/root/electron-quick-start/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-22T07_40_35_245Z-debug.log
```

The file /root/.npm/_logs/2017-12-22T07_40_35_245Z-debug.log is attached:
[2017-12-22T07_40_35_245Z-debug.log](https://github.com/electron/electron-quick-start/files/1581819/2017-12-22T07_40_35_245Z-debug.log)

I got this error on my own linux PC, on my working linux PC, on brand new cloud server, everywhere around me. I think it is not my fault. Please help.

**Comment by micfan** [comment] 2017-12-29 14:44
I failed ` $ npm install` on Windows7, NPM totally can not work....

```
(D:\programs\conda) J:\electron-quick-start>npm install

> electron@1.7.10 postinstall J:\electron-quick-start\node_modules\electron
> node install.js

J:\electron-quick-start\node_modules\electron\install.js:48
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26)
[                 .] - postinstall: info lifecycle electron@1.7.10~postinstall: Failed to exec postinstall script
```

**Comment by Ghostboy-287** [comment] 2018-01-01 07:33
try `sudo npm install --unsafe-perm=true --allow-root`

**Comment by karunkannan** [comment] 2018-01-05 00:21
I'm getting the same issue on a Mac, I've tried uninstalling Node.js and npm. This is for both this tutorial and for installing electron.

**Comment by pranavgade20** [comment] 2018-01-08 12:20
'sudo npm install --unsafe-perm=true --allow-root' worked for me.

Thanks Ghostboy-287

**Comment by SriVignesT-Hexaware** [comment] 2018-01-22 18:37
sudo apt install nodejs-legacy worked for me

**Comment by ckerr** [comment] 2018-03-12 13:31
Closing this as a duplicate of https://github.com/electron/electron-quick-start/issues/108

For future people searching for this, https://stackoverflow.com/questions/38935024/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0 has a straightforward answer.

**Closed by ckerr** 2018-03-12 13:31 UTC

**Comment by ridhwaans** [comment] 2019-02-09 01:14
Tried ```electron-quick-start``` using WSL
had the following
```
  1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
  3 2 info using npm@5.6.0
  4 3 info using node@v9.5.0
  5 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
  6 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
  7 6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
  8 7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
  9 8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/m    nt/c/Users/ridhwaan/Source/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/    snap/bin
 10 9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /mnt/c/Users/ridhwaan/Source/electron-quick-start
 11 10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
 12 11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
 13 12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
 14 13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
 15 13 verbose stack Exit status 1
 16 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
 17 13 verbose stack     at EventEmitter.emit (events.js:160:13)
 18 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 19 13 verbose stack     at ChildProcess.emit (events.js:160:13)
 20 13 verbose stack     at maybeClose (internal/child_process.js:943:16)
 21 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
 22 14 verbose pkgid electron-quick-start@1.0.0
 23 15 verbose cwd /mnt/c/Users/ridhwaan/Source/electron-quick-start
 24 16 verbose Linux 4.4.0-17763-Microsoft
 25 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
 26 18 verbose node v9.5.0
 27 19 verbose npm  v5.6.0
 28 20 error code ELIFECYCLE
 29 21 error errno 1
 30 22 error electron-quick-start@1.0.0 start: `electron .`
 31 22 error Exit status 1
 32 23 error Failed at the electron-quick-start@1.0.0 start script.
 33 23 error This is probably not a problem with npm. There is likely additional logging output above.
 34 24 verbose exit [ 1, true ]
```

**Comment by fbens** [comment] 2021-07-18 11:45
```
sudo npm install
```

problem resolved.
